Z_SHAPE = 100
NOTE_RANGE = 8
TICKS_PER_BEAT = 96
TIME_SLICE_PER_BEAT = 4
BEAT = 4
BAR = 2
NUM_TIMESTEPS = TIME_SLICE_PER_BEAT * BEAT * BAR

IMAGE_SHAPE = (NUM_TIMESTEPS, NOTE_RANGE, 1)
BATCH_SIZE = 256

EPOCHS = 50
D_ITER = 5

ID_LENGTH = 6
MAX_ID = 521142
